### ISSUE TITLE
Drag drop reorder no working

### ISSUE THREAD

**Issue by bajki** [shixia226/bootstrap-vue-designer#2]
Can't reorder components, on drop goes to bottom and not in the desired section.

**Comment by shixia226** [comment]
First select the components you want to reorder.
Second you can move the cursor up to the components and press the mouse for a while and then you can drag the selected compnents drop to anywhere.

**Comment by bajki** [comment]
![ezgif-3-45b61dde5b14](https://user-images.githubusercontent.com/24210611/53083684-acaf8680-34ff-11e9-97a3-e2499ec48264.gif)

**Comment by shixia226** [comment]
Sorry for without checking myself.
The issue now is resolved.
